module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Ataraxic',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Moose',
    'Peaceful',
    'Tranquil',
    'Amber',
    'June',
    'May',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Sunny',
    'Dusty',
    'Diamond',
    'Cool',
    'Serene',
    'Lilac',
    'Clement',
    'Pleasant'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]
